#!/usr/bin/env bash
# Phase 2 - Kubeflow core, via kustomize (community-distribution ${KF_VERSION})
#
# Everything here has no usable Helm chart:
#   * Istio glue CRs Kubeflow needs but the Istio charts don't ship
#   * dex + oauth2-proxy (Kubeflow-specific OIDC wiring)
#   * Pipelines (no Helm chart exists at all)
#   * Central Dashboard + profile-controller, Notebooks, Katib, user namespace
#
# Idempotent: re-running re-applies the same manifests.

source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"
require_cluster

# ---------------------------------------------------------------------------
step "Fetching kubeflow/community-distribution @ ${KF_VERSION}"
# ---------------------------------------------------------------------------
mkdir -p "${CACHE_DIR}"
if [[ -d "${MANIFESTS_DIR}/.git" ]]; then
  CURRENT="$(git -C "${MANIFESTS_DIR}" describe --tags --always 2>/dev/null || echo unknown)"
  if [[ "${CURRENT}" == "${KF_VERSION}" ]]; then
    ok "manifests already at ${KF_VERSION}"
  else
    warn "cached manifests at ${CURRENT}, re-cloning at ${KF_VERSION}"
    rm -rf "${MANIFESTS_DIR}"
  fi
fi
if [[ ! -d "${MANIFESTS_DIR}/.git" ]]; then
  git clone --depth 1 --branch "${KF_VERSION}" "${KF_REPO}" "${MANIFESTS_DIR}" 2>&1 | tail -1
  ok "cloned ${KF_VERSION}"
fi

# ---------------------------------------------------------------------------
step "Applying Istio resources Kubeflow needs (not shipped by the Istio charts)"
# ---------------------------------------------------------------------------
# common/istio/istio-install/base bundles the Istio install *and* four
# standalone CRs. We installed Istio itself with Helm, so apply just the CRs.
#   gateway.yaml                     - the Gateway all Kubeflow VirtualServices bind to
#   gateway_authorizationpolicy.yaml - ALLOW policy for the ingress gateway
#   deny_all_authorizationpolicy.yaml- mesh-wide default-deny
#   sidecar-prune-egress.yaml        - deferred: it declares Sidecars in the
#                                      kubeflow namespace, which the main
#                                      kustomize apply below creates.
ISTIO_BASE="${MANIFESTS_DIR}/common/istio/istio-install/base"
for f in gateway.yaml gateway_authorizationpolicy.yaml \
         deny_all_authorizationpolicy.yaml; do
  log "applying ${f}"
  retry 10 10 kubectl apply -f "${ISTIO_BASE}/${f}" >/dev/null
done
ok "Istio glue resources applied"

# ---------------------------------------------------------------------------
step "Generating hybrid kustomization"
# ---------------------------------------------------------------------------
# Mirrors example/kustomization.yaml, minus everything installed via Helm.
HYBRID_DIR="${MANIFESTS_DIR}/kubeflow-hybrid"
mkdir -p "${HYBRID_DIR}"

{
  cat <<'HEADER'
# GENERATED by scripts/02-kubeflow-core.sh - do not edit by hand.
# Derived from example/kustomization.yaml with the Helm-installed layers removed.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

sortOptions:
  order: legacy
  legacySortOptions:
    orderFirst:
    - Namespace
    - ResourceQuota
    - StorageClass
    - CustomResourceDefinition
    - MutatingWebhookConfiguration
    - ServiceAccount
    - PodSecurityPolicy
    - NetworkPolicy
    - Role
    - ClusterRole
    - RoleBinding
    - ClusterRoleBinding
    - ConfigMap
    - Secret
    - Endpoints
    - Service
    - LimitRange
    - PriorityClass
    - PersistentVolume
    - PersistentVolumeClaim
    - Deployment
    - StatefulSet
    - CronJob
    - PodDisruptionBudget
    orderLast:
    - ValidatingWebhookConfiguration

resources:
HEADER

  # --- auth: oauth2-proxy must precede dex ---
  echo "- ../common/oauth2-proxy/overlays/m2m-dex-only"
  echo "- ../common/dex/overlays/oauth2-proxy"

  # --- kubeflow base ---
  echo "- ../common/kubeflow-namespace/base"
  echo "- ../common/kubeflow-roles/base"
  echo "- ../common/istio/kubeflow-istio-resources/base"

  # --- optional knative (needed only for KServe Serverless) ---
  if [[ "${INSTALL_KNATIVE}" != "off" ]]; then
    echo "- ../common/knative/knative-serving/overlays/gateways"
    echo "- ../common/istio/cluster-local-gateway/base"
  fi

  [[ "${INSTALL_PIPELINES}" == "kustomize" ]] && echo "- ../applications/pipeline/overlays"
  [[ "${INSTALL_KATIB}"     == "kustomize" ]] && echo "- ../applications/katib/upstream/installs/katib-with-kubeflow"

  # Central Dashboard also brings profile-controller (Profile CRD) and
  # poddefaults webhooks - always required.
  echo "- ../applications/dashboard/overlays/istio"

  [[ "${INSTALL_NOTEBOOKS}" == "kustomize" ]] && echo "- ../applications/notebooks-v1/overlays/istio"
  [[ "${INSTALL_TRAINER}"   == "kustomize" ]] && echo "- ../applications/trainer/overlays"
  [[ "${INSTALL_TRAINING_OPERATOR}" == "kustomize" ]] && echo "- ../applications/training-operator/upstream/overlays/kubeflow"
  [[ "${INSTALL_KSERVE}"    == "kustomize" ]] && echo "- ../applications/kserve/kserve"
  [[ "${INSTALL_SPARK}"     == "kustomize" ]] && echo "- ../applications/spark/spark-operator/overlays/kubeflow"

  if [[ "${INSTALL_HUB}" != "off" ]]; then
    echo "- ../applications/hub/overlays/model-registry"
    echo "- ../applications/hub/overlays/model-catalog"
  fi

  # The default user profile / namespace. Must come after profile-controller.
  echo "- ../common/user-namespace/base"
} > "${HYBRID_DIR}/kustomization.yaml"

ok "wrote ${HYBRID_DIR}/kustomization.yaml"
grep -c '^- ' "${HYBRID_DIR}/kustomization.yaml" | xargs -I{} echo "     {} component(s) selected"

# ---------------------------------------------------------------------------
step "Rendering manifests"
# ---------------------------------------------------------------------------
RENDERED="${CACHE_DIR}/kubeflow-core.yaml"
kustomize build "${HYBRID_DIR}" > "${RENDERED}"
ok "rendered $(grep -c '^kind:' "${RENDERED}") resources -> ${RENDERED}"

# ---------------------------------------------------------------------------
step "Applying to cluster (retrying: CRs cannot land before their CRDs)"
# ---------------------------------------------------------------------------
# Upstream explicitly documents that the first applies fail. Server-side apply
# handles the large CRD annotations that would otherwise blow the annotation limit.
retry 15 20 kubectl apply --server-side --force-conflicts -f "${RENDERED}" >/dev/null \
  || die "manifests did not converge after 15 attempts"
ok "manifests applied"

# Deferred from the Istio glue step: these Sidecar resources live in the
# kubeflow namespace, which only exists after the apply above.
log "applying sidecar-prune-egress.yaml (needs the kubeflow namespace)"
retry 10 10 kubectl apply -f "${ISTIO_BASE}/sidecar-prune-egress.yaml" >/dev/null
ok "sidecar egress scoping applied"

# ---------------------------------------------------------------------------
step "Waiting for core namespaces"
# ---------------------------------------------------------------------------
wait_namespace_ready auth 600        || warn "dex not fully ready yet"
wait_namespace_ready oauth2-proxy 600 || warn "oauth2-proxy not fully ready yet"
wait_namespace_ready kubeflow 1200   || warn "some kubeflow pods are still settling"

# ---------------------------------------------------------------------------
step "Phase 2 summary"
# ---------------------------------------------------------------------------
kubectl get pods -n kubeflow
echo
kubectl get pvc -A
echo
ok "Phase 2 complete. Next: make apps"
